[package]
name = "dsse"
edition = "2024"
version = "0.1.0"
rust-version = "1.88.0"
description = "Library for the Dead Simple Signing Envelope (DSSE)"
homepage = "https://github.com/theupdateframework/rust-tuf"
repository = "https://github.com/theupdateframework/rust-tuf"
documentation = "https://docs.rs/dsse"
license = "MIT/Apache-2.0"
keywords = [ "security", "signing", "dsse" ]
categories = [ "cryptography" ]

[lib]
name = "dsse"
path = "./src/lib.rs"

[dependencies]
data-encoding = "2.10"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
serde_json = "1"
